### ISSUE TITLE
Please add Ahead of time compile support

### ISSUE THREAD

**Issue by metzc** [apollostack/angular2-apollo#119]
e.g. needed for Ionic 2 RC0

**Comment by stubailo** [comment]
Can you go into detail about what is blocking it from working?

**Comment by kamilkisiela** [comment]
@metzc I'm going to work on it but not in next few days. If anyone wants to create a PR, it would be nice :)

@stubailo An extended `tsc` but supports html etc. This way all templates are being compiled to js and external html and css is bundled within an app.

This way you get templates compiled to JS:

```js
// many of
document.createElement(/* ... */)
```

instead of:
```html
<input *ngIf="!something" [(ngModel)]="bar" />
```

**Comment by stubailo** [comment]
Sure, I guess I'm wondering why this repository has to be involved in that. Isn't compiling the code some other tool's problem?

**Comment by kamilkisiela** [comment]
It has few requirements and if I remember correctly `angular2-apollo` doesn't fulfills them (or at least one).   I haven't looked deeper into this, did a quick attempt to see if it works, that's all.

**Comment by metzc** [comment]
as @stubailo said there are requirements. This post has some useful hints: https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.pbg52i3qt

Part of the problem is also the apollo-client library where i created a seperate issue: https://github.com/apollostack/apollo-client/issues/758

I tried to do some fixes myself and i found out that the ApolloModule.withClient(client) method does not work that way with AOT. I could make it to work by changing the module code to the way it was done by ng2-translate: https://github.com/ocombe/ng2-translate/blob/master/ng2-translate.ts

This would break the tutorial and i think also requires changes i have done to the apollo-client library, so a pull request now wouldn't make sense i assume.

**Comment by vangorra** [comment]
Instead of using ```ApolloModule.withClient(APOLLO_CLIENT)```, I ended up using a provider factory. Here is my work around.

constants/ApolloClient.ts
```typescript
....
export const APOLLO_CLIENT = new ApolloClient({
    networkInterface: NETWORK_INTERFACE
});

export function apolloClientFactory(): ApolloClient {
    return APOLLO_CLIENT;
}
```

modules/AppModule.ts
```typescript
@NgModule({
...
providers: [
   ...
   {
        provide: Angular2Apollo,
        useFactory: apolloClientFactory
    }
]
```

**Comment by kamilkisiela** [comment]
DONE! :rocket: #124

**Comment by kamilkisiela** [comment]
And [an example](https://github.com/apollostack/angular2-apollo/tree/master/examples/hello-world)

**Comment by geocine** [comment]
for some reason I could still now make your example work  on ionic. I am using the correct versions of packages?
```
"angular2-apollo": "^0.8.0",
"apollo-client": "^0.5.2",
```

**Comment by geocine** [comment]
Sorry I have now solved it , I did not notice it should be

```
export {
    client
}
```

not
```
export const client = ...
```

**Comment by Dunos** [comment]
I still get the error "Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function" when using `ApolloModule.withClient(client)`, any idea why?
