### ISSUE TITLE
ng serve - Error encountered resolving symbol values statically - with ng 2.2.3

### ISSUE THREAD

**Issue by manuelfink** [apollostack/angular2-apollo#197]
I just updated to the latest angular version (angular 2.2.3 with angular-cli 1.0.0-beta.22-1).

Now I get an error running ng serve.

`10% building modules 2/2 modules 0 activeError: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in  ./src/app/app.module.ts, resolving symbol AppModule in ./src/app/app.module.ts`

Commenting out all apollo related code the app start again. The problem seems to be the function calls within app.module.ts. 

@Urigo 

* Whats the proper way to import in apolli client in the latest version of ng2?
* You may like to update docs?

I'm trying to use it like described in the docs http://dev.apollodata.com/angular2/initialization.html

**Comment by kamilkisiela** [comment]
We have a solution but we still working on it. It should be released soon :)

**Comment by kamilkisiela** [comment]
Should be fixed by #195

**Comment by manuelfink** [comment]
You re fast. Awesome guys! Can you update the docs with an sample on how to use it?

**Comment by kamilkisiela** [comment]
apollostack/angular2-docs#23 :)

**Comment by kamilkisiela** [comment]
And [a working example](https://github.com/apollostack/angular2-apollo/tree/master/examples/hello-world)

**Comment by mugash** [comment]
I get the error "Error encountered resolving symbol values statically. Calling function 'ApolloClient', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function"
when using angular  "2.3.1"  and angular cli version 1.0.0-beta.24.Can someone help please.
I have tried to upgrade angular2-apollo to the latest version but still doesn't work.

**Comment by kamilkisiela** [comment]
@mugash @manuelfink for now as a workaround you can try this:

```ts
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { ApolloModule, AngularApolloClient } from 'angular2-apollo';

import { client } from './apollo'; // instance of ApolloClient
import { AppComponent } from './app.component';

export function provideClient() {
    return client;
}

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    ApolloModule,
  ],
  providers: [{
    provide: AngularApolloClient,
    useFactory: provideClient
  }],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

Don't know if it will work though.

**Comment by manuelfink** [comment]
@kamilkisiela implementing an auth guard I wrapped apollo into an own service. Not sure if this is a good idea though? Is this an good idea or any drawback through it? https://github.com/apollostack/angular2-apollo/issues/142

**Comment by kamilkisiela** [comment]
Okay, `0.9.0-rc.1` is now available
